services:
  - type: web
    name: skillforge
    env: python
    plan: free
    buildCommand: ./render-build.sh
    startCommand: gunicorn skillforge.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skillforge-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: skillforge.settings
databases:
  - name: skillforge-db
    plan: free
